import { Model } from '../types';

export const MODEL_MANIFEST: Model[] = [
  {
    id: 'Llama-3.2-3B-Instruct-q4f16_1-MLC',
    name: 'Llama 3.2 3B',
    runtime: 'WEBLLM',
    size: '1.8 GB',
    sizeBytes: 1932735283,
    tags: ['FAST', 'MOBILE OPTIMIZED'],
    status: 'NOT_INSTALLED',
    description: 'Meta\'s Llama 3.2 3B Instruct model. Optimized for mobile devices with high quality and speed.',
    recommendation: 'Best for Galaxy S25 and modern Android phones. Fast and capable.',
    provider: 'Meta',
    format: 'MLC',
    quantization: 'q4f16_1',
    ramRequirementGB: 4,
    storageRequirementGB: 2,
    recommendedDevices: ['Galaxy S25', 'Pixel 9', 'iPhone 15 Pro']
  },
  {
    id: 'Qwen2.5-3B-Instruct-q4f16_1-MLC',
    name: 'Qwen 2.5 3B',
    runtime: 'WEBLLM',
    size: '1.9 GB',
    sizeBytes: 2040109465,
    tags: ['BALANCED', 'MOBILE'],
    status: 'NOT_INSTALLED',
    description: 'Alibaba\'s Qwen 2.5 3B model. Exceptional performance for its size, especially in math and coding.',
    recommendation: 'Perfect for high-end mobile devices like Galaxy S25. Very balanced and capable.',
    provider: 'Alibaba',
    format: 'MLC',
    quantization: 'q4f16_1',
    ramRequirementGB: 4,
    storageRequirementGB: 2.2
  },
  {
    id: 'Qwen2.5-Coder-3B-Instruct-q4f16_1-MLC',
    name: 'Qwen 2.5 Coder 3B',
    runtime: 'WEBLLM',
    size: '1.9 GB',
    sizeBytes: 2040109465,
    tags: ['CODING', 'MOBILE'],
    status: 'NOT_INSTALLED',
    description: 'Specialized coding version of Qwen 2.5 3B. Highly capable at programming tasks.',
    recommendation: 'Best for developers on mobile. Fast and accurate coding assistance.',
    provider: 'Alibaba',
    format: 'MLC',
    quantization: 'q4f16_1',
    ramRequirementGB: 4,
    storageRequirementGB: 2.2
  },
  {
    id: 'gemma-2-2b-it-q4f16_1-MLC',
    name: 'Gemma 2 2B',
    runtime: 'WEBLLM',
    size: '1.6 GB',
    sizeBytes: 1717986918,
    tags: ['EFFICIENT', 'GOOGLE'],
    status: 'NOT_INSTALLED',
    description: 'Google\'s latest Gemma 2 2B model. Offers state-of-the-art performance for its compact size.',
    recommendation: 'Highly recommended for Galaxy S25. Exceptional quality-to-size ratio.',
    provider: 'Google',
    format: 'MLC',
    quantization: 'q4f16_1',
    ramRequirementGB: 3,
    storageRequirementGB: 1.8
  },
  {
    id: 'DeepSeek-R1-Distill-Qwen-1.5B-q4f16_1-MLC',
    name: 'DeepSeek R1 Qwen 1.5B',
    runtime: 'WEBLLM',
    size: '1.1 GB',
    sizeBytes: 1181116006,
    tags: ['REASONING', 'FAST'],
    status: 'NOT_INSTALLED',
    description: 'DeepSeek R1 distilled model based on Qwen 1.5B. Specialized in complex reasoning and logic.',
    recommendation: 'Best for logical tasks on mobile. Very fast reasoning.',
    provider: 'DeepSeek',
    format: 'MLC',
    quantization: 'q4f16_1',
    ramRequirementGB: 2,
    storageRequirementGB: 1.2
  }
];
