import { ModelManifest } from "../types";

export const MODEL_MANIFEST: ModelManifest[] = [
  {
    modelId: "Llama-3.2-1B-Instruct-q4f32_1-MLC",
    canonicalName: "Llama 3.2 1B Instruct",
    alias: "llama3.2-1b",
    provider: "meta",
    quantization: "q4f32_1",
    artifactUrls: ["https://huggingface.co/mlc-ai/Llama-3.2-1B-Instruct-q4f32_1-MLC/resolve/main/model.tar.gz"],
    expectedSha256: null,
    totalBytes: 1200000000,
    minRAM: 2,
    recommendedRAM: 4,
    visionSupport: false,
    tags: ["instruct", "llama3.2", "small", "recommended"]
  },
  {
    modelId: "Llama-3.2-3B-Instruct-q4f32_1-MLC",
    canonicalName: "Llama 3.2 3B Instruct",
    alias: "llama3.2-3b",
    provider: "meta",
    quantization: "q4f32_1",
    artifactUrls: ["https://huggingface.co/mlc-ai/Llama-3.2-3B-Instruct-q4f32_1-MLC/resolve/main/model.tar.gz"],
    expectedSha256: null,
    totalBytes: 2800000000,
    minRAM: 4,
    recommendedRAM: 8,
    visionSupport: false,
    tags: ["instruct", "llama3.2", "medium"]
  },
  {
    modelId: "Qwen2.5-1.5B-Instruct-q4f32_1-MLC",
    canonicalName: "Qwen 2.5 1.5B Instruct",
    alias: "qwen2.5-1.5b",
    provider: "alibaba",
    quantization: "q4f32_1",
    artifactUrls: ["https://huggingface.co/mlc-ai/Qwen2.5-1.5B-Instruct-q4f32_1-MLC/resolve/main/model.tar.gz"],
    expectedSha256: null,
    totalBytes: 1400000000,
    minRAM: 2,
    recommendedRAM: 4,
    visionSupport: false,
    tags: ["instruct", "qwen2.5", "small"]
  },
  {
    modelId: "Qwen2.5-0.5B-Instruct-q4f32_1-MLC",
    canonicalName: "Qwen 2.5 0.5B Instruct",
    alias: "qwen2.5-0.5b",
    provider: "alibaba",
    quantization: "q4f32_1",
    artifactUrls: ["https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f32_1-MLC/resolve/main/model.tar.gz"],
    expectedSha256: null,
    totalBytes: 600000000,
    minRAM: 1,
    recommendedRAM: 2,
    visionSupport: false,
    tags: ["instruct", "qwen2.5", "tiny"]
  },
  {
    modelId: "SmolLM2-360M-Instruct-q4f32_1-MLC",
    canonicalName: "SmolLM2 360M Instruct",
    alias: "smollm2-360m",
    provider: "huggingface",
    quantization: "q4f32_1",
    artifactUrls: ["https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/model.tar.gz"],
    expectedSha256: null,
    totalBytes: 400000000,
    minRAM: 1,
    recommendedRAM: 2,
    visionSupport: false,
    tags: ["instruct", "smollm2", "tiny"]
  },
  {
    modelId: "Llama-3.1-8B-Instruct-q4f32_1-MLC",
    canonicalName: "Llama 3.1 8B Instruct (FP32)",
    alias: "llama3.1-8b-fp32",
    provider: "meta",
    quantization: "q4f32_1",
    artifactUrls: ["https://huggingface.co/mlc-ai/Llama-3.1-8B-Instruct-q4f32_1-MLC/resolve/main/model.tar.gz"],
    expectedSha256: null,
    totalBytes: 5400000000,
    minRAM: 12,
    recommendedRAM: 16,
    visionSupport: false,
    tags: ["instruct", "llama3.1", "large"]
  },
  {
    modelId: "Mistral-7B-Instruct-v0.3-q4f32_1-MLC",
    canonicalName: "Mistral 7B v0.3 (FP32)",
    alias: "mistral-7b-fp32",
    provider: "mistral",
    quantization: "q4f32_1",
    artifactUrls: ["https://huggingface.co/mlc-ai/Mistral-7B-Instruct-v0.3-q4f32_1-MLC/resolve/main/model.tar.gz"],
    expectedSha256: null,
    totalBytes: 4800000000,
    minRAM: 12,
    recommendedRAM: 16,
    visionSupport: false,
    tags: ["instruct", "mistral"]
  },
  {
    modelId: "Phi-3-mini-4k-instruct-q4f32_1-MLC",
    canonicalName: "Phi-3 Mini 4K (FP32)",
    alias: "phi3-mini-fp32",
    provider: "microsoft",
    quantization: "q4f32_1",
    artifactUrls: ["https://huggingface.co/mlc-ai/Phi-3-mini-4k-instruct-q4f32_1-MLC/resolve/main/model.tar.gz"],
    expectedSha256: null,
    totalBytes: 2600000000,
    minRAM: 6,
    recommendedRAM: 8,
    visionSupport: false,
    tags: ["instruct", "phi3"]
  },
  {
    modelId: "gemma-2b-it-q4f32_1-MLC",
    canonicalName: "Gemma 2B IT (FP32)",
    alias: "gemma-2b-fp32",
    provider: "google",
    quantization: "q4f32_1",
    artifactUrls: ["https://huggingface.co/mlc-ai/gemma-2b-it-q4f32_1-MLC/resolve/main/model.tar.gz"],
    expectedSha256: null,
    totalBytes: 1800000000,
    minRAM: 4,
    recommendedRAM: 6,
    visionSupport: false,
    tags: ["instruct", "gemma"]
  }
];
